### ISSUE TITLE
Bridge mode not working

### ISSUE THREAD

**Issue by WifiHero91** [Xinyuan-LilyGO/T-Halow#10]
Dear Lilygo!

I got the two T-halow but in bridge mode it is not working. They connected state got by AT+CONN_STATE command but none of a packet go trought the bridge. I read some other buyer has the same issue and they got now chips what solved the problem. 

Please send me the right chips. 

mail@vargaimre.hu
order number: LILYGO-25417

Thank you!
Kind Regards,
Imre Varga

**Comment by WifiHero91** [comment]
It is still problem. I bought product what is not working and Lilygo support doesnt want to solve it.

**Comment by ShallowGreen123** [comment]
You can try sending `AT+LOADDEF=1` to reset each T-Halow, and then try it again in your own way;

Note that after assigning the address, ping the address of the `Ethernet adapter Ethernet` network segment

**Comment by WifiHero91** [comment]
What is Ethernet adapter Ethernet network segment?  Do i need to ping my ethernet interface address? It doesn't matter because BROADCAST messages doesn't go over the WB. For Broadcast messages you dont need the ARP table..... 
Please send new flash like alphafox02 with the right WB version!

**Comment by ShallowGreen123** [comment]
You can try to use `AT+VERSION=?` to check the firmware version of the TX-AH module. The firmware in bridge mode is `VERSION:v1.6.4.3-xxxxx`.

If it is another version, please replace the firmware chip that comes with lilygo;

If there is no `VERSION:v1.6.4.3-xxxxx` firmware chip, you can ask after-sales service to send you a replacement one.

**Comment by WifiHero91** [comment]
![at+version_output](https://github.com/user-attachments/assets/22bc74b2-4d2b-44de-b53d-a377b9ce34a3)

Thank You! The version is different!

**Comment by WifiHero91** [comment]
@ShallowGreen123  What is email address where I can ask for new flash?

**Comment by ShallowGreen123** [comment]
It seems that the firmware version is wrong if it doesn't work;

There should be a flash chip in the product package, just replace it; here is a demonstration video:
https://www.youtube.com/watch?v=nM2GE8Imshc

If there is indeed no flash in the product package, contact after-sales service to reissue it; or after seeing this reply, confirm that there is no flash in the product package, I can also help feedback;

**Comment by WifiHero91** [comment]
![at+version_output_other_flash](https://github.com/user-attachments/assets/a508ff3d-8ad2-4038-b5b9-17d555a2f5e9)
I changed to the other flash in the zip lock bag and also got different version.

**Comment by ShallowGreen123** [comment]
It seems that I did not send you the correct bridge firmware, you can give feedback to the after-sales

**Comment by WifiHero91** [comment]
I send feedback and hope the new flash will be arrive soon.

**Comment by WifiHero91** [comment]
I got the flash but i think they are completly empty. The output.:

[  3114][I][esp32-hal-i2c.c:75] i2cInit(): Initialising I2C Master: sda=7 scl=6 freq=100000
OLED FeatherWing test
E (3040) camera: Camera probe failed with error 0x105(ESP_ERR_NOT_FOUND)
Camera init failed with error 0x105[  3149][W][sd_diskio.cpp:174] sdCommand(): no token received
[  3250][W][sd_diskio.cpp:174] sdCommand(): no token received
[  3350][W][sd_diskio.cpp:174] sdCommand(): no token received
[  3450][E][sd_diskio.cpp:199] sdCommand(): Card Failed! cmd: 0x00
[  3450][W][sd_diskio.cpp:516] ff_sd_initialize(): GO_IDLE_STATE failed
[  3451][E][sd_diskio.cpp:802] sdcard_mount(): f_mount failed: (3) The physical drive cannot work
[  3460][W][sd_diskio.cpp:174] sdCommand(): no token received
[  3565][W][sd_diskio.cpp:174] sdCommand(): no token received
[  3666][W][sd_diskio.cpp:174] sdCommand(): no token received
[  3767][E][sd_diskio.cpp:199] sdCommand(): Card Failed! cmd: 0x00
Card Mount Failed
AT+SYSDBG ERROR
AT+BSS_BW FAILD
AT+MODE=STA FAILD
******************************
TX-AH    ---
SSD1306  ---
SDCard   ---
CAMERA   ---
 
Role:          STA 
Disconnect!!!
******************************
TX-AH    ---
SSD1306  ---
SDCard   ---
CAMERA   ---
 
Role:          STA 
Disconnect!!!

**Comment by WifiHero91** [comment]
![image0 (1)](https://github.com/user-attachments/assets/3974a38c-0374-48f5-b19e-a630b525c0af)
 That was written on the zip lock bag.

**Comment by WifiHero91** [comment]
I got two new flash from Lilygo with the bridge mode and start to work as it has to.
