### ISSUE TITLE
AP-STA-net-AP-STA and pair button feedback

### ISSUE THREAD

**Issue by alphafox02** [Xinyuan-LilyGO/T-Halow#12]
Just letting you all know, I can confirm that traffic passed between 2 relay nodes. What I mean is that if you laid three distinct pairs down on a table and put an Ethernet cable between device 2 and 3 and between 4 and 5, the traffic will flow from a PC hooked to device one to a PC connected to device 6.

I'm the one testing the drone setup. I believe my initial problem was that I received 4 devices that had already had some configuration done and what I needed to do was to wipe all previous pairings. 

As far as the pair buttons - I've only seen two out of four devices light the connect red light when pushing the pair button and I can't be for certain the mode switch is in fact changing the mode. Instead I've been doing it with AT commands.

**Comment by Duan-GX** [comment]
Do you mean the following? If so, the data from node 1 can flow to node 6. That is, the two PCs can ping each other.

![image](assets/image-20241016092403-cfic8ig.png)

For version 1 of T-Halow, COMMECT's light stays on only after the connection is successful; At other times, the COMMECT blinks when you hold down the PAIR key. If there is no phenomenon when you press the PAIR key for a long time, you can open the serial port to see if there is any information output when the PAIR key is pressed. If not, the PAIR may be broken.

Want to determine if the mode switch is working. You can open the serial port, and then flip the mode switch to see whether the serial port has output (to avoid interference, you can use `AT+SYSDBG=LMAC,0` to turn off the debug message).

**Comment by Duan-GX** [comment]
Do you mean the following? If so, the data from node 1 can flow to node 6. That is, the two PCs can ping each other.
![image](https://github.com/user-attachments/assets/3cf2ad53-7834-458b-a030-18580eada79a)
For version 1 of T-Halow, COMMECT's light stays on only after the connection is successful; At other times, the COMMECT blinks when you hold down the PAIR key. If there is no phenomenon when you press the PAIR key for a long time, you can open the serial port to see if there is any information output when the PAIR key is pressed. If not, the PAIR may be broken.

Want to determine if the mode switch is working. You can open the serial port, and then flip the mode switch to see whether the serial port has output (to avoid interference, you can use `AT+SYSDBG=LMAC,0` to turn off the debug message).

**Comment by alphafox02** [comment]
Yes, the diagram works as you show. 

For pairing. Only two out of the four I have (version 1) light the connect light when pushing the pair button. 

I’ll investigate further. I ended up using AT commands to set mode and conduct pair. I’ll check via serial again and see if switch is changing mode. 

I do have one situation where I have an old model and a new model paired. When I turn them off and back on the pair is not successful until I reboot the newer model by pushing the button close to the Ethernet port if I recall (some kind of reboot) and almost immediately it comes back on and link is successful confirmed with rssi lights and connect all being lit. 

I will update ticket with findings, but so far besides the few things I mention, it’s working well.

**Comment by alphafox02** [comment]
What commands would you suggest running in order to put each pair on say 4Mhz wide bandwidth and 3 unique frequencies/channels? 

I’m first going to repair my 6 units into groups according to old hardware and new hardware. I have two out of 3 pairs mix matched. I’d like to see if that helps resolve some of my intermittent connection issues and if not I’ll try the bandwidth and channel change.

**Comment by alphafox02** [comment]
After paying closer attention while testing again today I've found that out of the four new style T-Halow's I have, 1 is an AP and 3 are a STA when dealing with bridge mode. Regardless of the switch position or AT commands, the mode will not change. What will happen is if I boot one up after changing it from STA to AP via AT+MODE=AP, upon reboot it'll revert to STA confirmed by checking serial output AT+WNBCFG. If I push the button beside the ethernet port to trigger a reboot, it will in fact change modes and only stay in the mode I want it to be in until another power cycle.

That probably sounds confusing, but it's what I'm observing. So to proceed with my test I used 5x T-Halow devices. I pair an old one set to STA mode to the one new unit that was shipped to me in AP mode. I then used an old one and put it into AP mode and used two other new devices in STA mode to connect to it. This still allowed me to test a connection across two drones by having only one drone use the ethernet between devices.

However, there's still an issue sometimes where all devices will be connected, yet a ping will not go across. Even if I bring all the devices back close together. I'll have to power cycle everything and then suddenly the ping will work perfectly fine for some time.

**Comment by alphafox02** [comment]
I just noticed though that the pair button seems to have no effect, connect light doesn't light, and while observing via console connection there's no sign on the AP that it's going to pair mode. I'll flash my other three and manually put them in pair mode and continue testing.
