### ISSUE TITLE
Using LilyGo T-Halow - ESP32 Wireless Network instead of Ethernet Network

### ISSUE THREAD

**Issue by f2ka07** [Xinyuan-LilyGO/T-Halow#13]
I recently acquired two T-Halow modules and configured IP addresses through the Ethernet bridge. However, when I disconnect the Ethernet cable, they lose connectivity.  This is expected, but can we connect the T-Halow devices to a wireless network instead of an Ethernet one?  For instance, can T-Halow get wireless LAN connectivity from ESP32?

**Comment by ShallowGreen123** [comment]
You can try to use `AT+VERSION=?` to check the firmware version of the TX-AH module. The firmware in bridge mode is `VERSION:v1.6.4.3-xxxxx`. If it is another version, please replace the firmware chip that comes with lilygo to see if it can help you solve the problem.

here is a demonstration video:
[https://www.youtube.com/watch?v=nM2GE8Imshc](https://www.youtube.com/watch?v=nM2GE8Imshc)

**Comment by f2ka07** [comment]
I got stuck because I encountered another issue with one of the T-Halow devices.   It doesn't respond to the AT command. The only output it gives is as below. Sometimes the output comes from USB C and other times in the other USB. What could be the issue?

ESP-ROM:esp32s3-20210327
OLED FeatherWing test
Camera init failed with error 0x105Card Mount Failed
AT+SYSDBG ERROR
AT+BSS_BW FAILD
AT+MODE=STA FAILD
******************************
TX-AH    ---
SSD1306  ---
SDCard   ---
CAMERA   ---
 
Role:          STA 
Disconnect!!!
******************************
TX-AH    ---
SSD1306  ---
SDCard   ---
CAMERA   ---
 
Role:          STA 
Disconnect!!!
******************************
TX-AH    ---
SSD1306  ---
SDCard   ---
CAMERA   ---
 
Role:          STA 
Disconnect!!!
