### ISSUE TITLE
Flash chip comes pre-flashed with firmware?

### ISSUE THREAD

**Issue by abu-matterize** [Xinyuan-LilyGO/T-Halow#14]
Hello there,

I brought T-Halow and tried to communicate with TX-AH module via AT commands with microUSB port. But failed.

Do I need to flash the firmware to do so? Or is there a way I can communicate via ESP32 out of the box?

**Comment by abu-matterize** [comment]
After USB-C is plugged - Solid green light. Opening JTAG port with 115200 prints,
```bash
[369424]send assoc request to 22:9f:f1:a2:8d:28, ssid= (freq:8660)
+DISCONNECT
******************************
TX-AH   PASS
SSD1306  ---
SDCard   ---
CAMERA   ---
 
Role:          STA 
Disconnect!!!

[372870]send assoc request to 22:9f:f1:a2:8d:28, ssid= (freq:8660)
[373232]send assoc request to 22:9f:f1:a2:8d:28, ssid= (freq:8660)
[374714]send assoc request to 22:9f:f1:a2:8d:28, ssid= (freq:8660)
+DISCONNECT
******************************
```

**Comment by alphafox02** [comment]
Please refer to this video I put together. Since you’ve mentioned micro usb port I am making the assumption you have the older hardware.

Not all applications open and communicate correctly with the micro usb port which is what you need to connect to for the purposes of sending AT commands. You can likely find the windows version of this application and follow along as needed, but I used Linux.

https://www.youtube.com/watch?v=vZjUTUHTOX4

**Comment by abu-matterize** [comment]
The label in the hardware says: `T-Halow V1.0 24-05-31`

**Comment by abu-matterize** [comment]
And it's print,
```
cca: 4s st12= 0:0 mid1224= 0:0:0:0 ed1224= 0:0:0:0 ch_bz= 0
chip-temperature:47, vcc:3.30, vdd13b:1.34, vdd13c:1.33
sta_list: no sta
```
every 2 seconds.

**Comment by alphafox02** [comment]
Yep, use the chips provided that came in separate bags. I can’t speak to the hardware confidently as you’re mentioning you have a micro usb port. I have two hardware models, the older ones that had micro usb and usbc ports and newer hardware that has just usbc port but also has a mode switch for ap/sta and a pair button.

If you’re now seeing output like you’ve shown above on the micro usb port, you should be able to issue AT commands.

**Comment by alphafox02** [comment]
If you’re simply trying to use them to setup a wireless bridge mode, meaning you can plug a laptop into each one and be able to ping from laptop to laptop, then check out the video I shared. You should be able to give AT commands to make one an AP and one a STA and then initiate a pairing process once. Once complete, you’ll be able to communicate across. 

If you’re trying to setup one of the other modes, you’ll have to refer to the info lilygo provided. I’ve only focused on bridge mode so far.

**Comment by abu-matterize** [comment]
Here it is.
![T-Halow](https://github.com/user-attachments/assets/c06199c4-0543-4760-85bd-877d506135f1)

**Comment by abu-matterize** [comment]
I'm looking to get the `AT` commands working initially.

**Comment by alphafox02** [comment]
Yep, I have that version too - just the 900mhz one instead. The video and steps I mention above should assist you assuming there’s no problems with the chips you inserted. Pay super close attention to the markings and dot on them as I accidentally briefly put one in to the seat incorrectly. Since you’re seeing output on micro usb you of course have if in correct.

**Comment by abu-matterize** [comment]
I'm using `picocom`, I tried with `serialportassistant` as well, but the results are same.

**Comment by abu-matterize** [comment]
I've 2 devices, one replaced flash chip came with bag and another as it's out of box. The log is only printed from the flash swapped device.

**Comment by alphafox02** [comment]
Each device should’ve came with a chip in a bag, based on my knowledge of the older devices like you have. 

You need to replace the flash chip of each one with the chip in the bag. 

Then perform the steps according to lilygo images or my video.

I don’t see in any of your screen shots above where you are issuing AT commands.

**Comment by abu-matterize** [comment]
Okay. I replaced flash chips for both devices. Here is the command I've issued and received no response.
```bash
*** local echo: yes ***
AT+MODE?
[62723]
LMAC STATUS:
local: 22:9f:f1:9c:9e:40 AID= 0
freq= 866.0 bw=2 chn=3 bgr=-60 iq=0:50:-1:0 dc=0:0(7:-1) tx=*5 dly=64:0:0 sif:rsp=0:0(0)
chn:  866.0 
bgr:    -60 
buf: free=78 tq=0 sq=0 ac=0:0:0:0 agg=0:0:0:0 statq=0 rxq=0:0 skb=0:0 rxb=120K
irq: ac=0 bkn=0 bo(rts:frm)=0:0:0:0:0 to(rts:frm)=0:0 rx=15
tx : cnt=0 dly=0:0ms mcast(bw:mcs)=2:0 agg=0(6027,0:0) data=0KB(0kbps) dur=0ms cca=0 per=0% est_rate=0kbps fail=0 drop=0
rx : cnt=15 bus=0ms cts_bm=0:0 pks=15 data=1KB(1kbps) dur= 6ms err(phy:fcs)=0:0 ecode=0x0 rssie= 0:0 cache_rxq= 0:0
dbg: dtmd=0:0:0 stamap=0x0 sleepmap=0x0 flag=0x0 rxdp=0 kerr=0 mic=0 lerr=0 kick=0 csc=0 rst=0 ovf=0 nob=0 tsnr=0 rssi=0 rxdut=0% txp=0 rxg=5    
cca: 4s st12= 0:0 mid1224= 0:0:0:0 ed1224= 0:0:0:0 ch_bz= 0
chip-temperature:45, vcc:3.31, vdd13b:1.31, vdd13c:1.31
sta_list: no sta
```

**Comment by abu-matterize** [comment]
Okay. Seems like AT command is responding.

**Comment by alphafox02** [comment]
Yep that shows you it’s working. If you refer to the video I linked you to it shows you all the steps or issue the commands per the documentation.

For example on 1
AT+MODE=AP

on 2
AP+MODE=STA

on both while leaving both powered 
AT+PAIR=1

look for successful pair then on both 
AT+PAIR=0

**Comment by abu-matterize** [comment]
The behaviour is related to `picocom` it seems. When I copy paste and hit return, `AT` command responds, but when I type it in, no response.

**Comment by alphafox02** [comment]
You can then plug one into your home router, for example, and plug your laptop into another. If everything is working, you should get DHCP from your home router.

**Comment by alphafox02** [comment]
> The behaviour is related to `picocom` it seems. When I copy paste and hit return, `AT` command responds, but when I type it in, no response.

Interesting, yeah I use what I showed in the video as that worked great for me.

**Comment by abu-matterize** [comment]
Alright. It's paired.

```bash
STA0: 22:9f:f1:73:52:40
tx0: mcs=*1 bw=2MHz snr=54 cnt=16 agg=1 data=1KB(2kbps) dur=11ms dut=50% txq=0 cca=102 ack=1KB(16) drop=0KB(0) per= 0%
rx0: mcs=0 bw=2MHz evm(avg:std)=0:0 rssi=-13 agc=0 cnt=27 agg=1 data=1KB(2kbps) dur=11ms dut=49% fcsErr=0, freqDev=-381Hz adv_bw=0:0:0:0
```

**Comment by abu-matterize** [comment]
By the way, does it required to append `CR LF` at the end? What's the raw frame looks like?

**Comment by alphafox02** [comment]
Not sure, I’ve not used more advanced commands/setup yet.

**Comment by abu-matterize** [comment]
Thanks for your help man.

**Comment by abu-matterize** [comment]
Interestingly, it's not pasted and hit return. Once pasted - it response back.

**Comment by abu-matterize** [comment]
Just a quick question @alphafox02 - Did you managed to work with WiFi STA and AP mode building a bridge instead of the Ethernet connections?

**Comment by alphafox02** [comment]
Please explain more. 

I was mainly focused on the bridge from AP to STA or STA AP STA and being able to have devices plugged in via Ethernet communicate across. In those configurations things have worked. But in both configurations, the bridge is built across the Halow wireless bridge. 

I’ve also tested multiple pairs on drones, but that gets a little more complicated.

**Comment by abu-matterize** [comment]
Here is my thought. I'm planning to setup first t-halow (TX-AH) as an AP and the same as an WiFi AP. And the second t-halow (TX-AH) as an STA with WiFi AP.

If I connect first WiFi AP to device 1 and second WiFi AP to device 2 and assign IP address, will I be able to ping each other?
