### ISSUE TITLE
How to work wifi camera at 900Mhz band ?

### ISSUE THREAD

**Issue by dinosauria123** [Xinyuan-LilyGO/T-Halow#17]
I tried your CameraWebServer.ino example and I found it can transfer camera image at 2.5GHZ band SSID wifi network.

How can I transfer image at 900 MHz band?

**Comment by dinosauria123** [comment]
Sorry, I found CameraWebServer.ino is not for 900MHz band.

I move to  TX_AH_Rx00p_AP.ino but I got

AT+SYSDBG ERROR
AT+BSS_BW FAILD
AT+MODE=AP FAILD

I need to setup flash memory ?

**Comment by dinosauria123** [comment]
I use Ubuntu Linux terminal.

AT commands success  /dev/ttyUSB0 (MicroUSB) but fails /dev/ttyACM0 (USB-C).

It seems  sendAT() function to send AT Command via USB-C ?

**Comment by dinosauria123** [comment]
I could connect two T-Halow board by input AT command manually.

[208550]wnb: pairing done, save wnb config!

[208553]erase flash, 1 sectors ...

[208618]write flash, 844 bytes ...

[208622]verify flash ... OK

[208623]switch syscfg partition ... OK

[208626]syscfg_write OK! (addr:ff000, crc=68c0, size:844, last_addr:fe000)

[215961]add_sta: aid= 1 6a:9c:00:92:94:78

[215963]wnb: [6a:9c:00:92:94:78] connect success!

But I could not get ping back to another PC.

My flash firmware version is v1.6.3.3-26347.

**Comment by ShallowGreen123** [comment]
May I see a picture of your device?

There is a firmware problem with the TX-AH module of your device; If you have a downloader, you can refer to the [documentation](https://github.com/Xinyuan-LilyGO/T-Halow?tab=readme-ov-file#firmware-download) and burn the [firmware of the TX-AH](https://github.com/Xinyuan-LilyGO/T-Halow/tree/master/firmware) module yourself;

If not, I can only give you a return for another, I'm sorry;

**Comment by dinosauria123** [comment]
Thank you for your reply !

I could burn firmware huge-ic-ah_v1.6.4.3-29063_2024.8.16_WNB.bin, Now I can ping back to another PC, fine.

I would like transfer image one to another T-Halow board.

It seems mode2 (Bridge mode) is promising because it may access by IP address.
I am looking for the way to set IP address of ESP32 camera within a T-halow network.

Any helps do you have ?

**Comment by dinosauria123** [comment]
A picture of my board.
![board](https://github.com/user-attachments/assets/fd3a52a1-c8da-4780-92f9-4e3afd1cb429)

I could burn firmware by cheap CH341A board.
![burn](https://github.com/user-attachments/assets/05d56300-f508-449b-8f4f-42fa37723995)

**Comment by ShallowGreen123** [comment]
Well done;

Regarding the setting of ESP32 camera address in T-Halow, the TaiXin official did not provide more detailed chip and image transmission related information;

So I may not be able to help you with that;

**Comment by dinosauria123** [comment]
I am very sad to hear this information ( T T )

I hope TaiXin open information and T-Halow can transfer image as easy as M5Camera....
