### ISSUE TITLE
Windows driver for USB 2.0 device

### ISSUE THREAD

**Issue by x893** [Xinyuan-LilyGO/T-Halow#6]
Hello,
I write firemware huge-ic-ah_v1.6.3.5-25403_2023.10.20_TAIXIN-usb.bin to module.
After connect To microUSB **J3** not data to/from terminal.
But if I connect IOA12/IOA13 to USB-DP/USB-DM, I see device USB 2.0 in windows device manager.
Only I can't find deriver for it. VID A012/ PID 4002
Can you help me with driver ?

Thanks in advance
Mitek

**Comment by aliosa27** [comment]
no windows driver, but it works with the linux driver on the taixin download page

**Comment by x893** [comment]
> no windows driver, but it works with the linux driver on the taixin download page

Thanks. You means
huge-ic-fmac-linux-driver-v2.2.1-26364 ?
